language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=src/ -m unittest discover -s src/test -t src/test
  - coverage report -m